/// Namespace for the AIDA detector description toolkit
namespace DD4hep {

  /// Namespace for the AIDA detector description toolkit supporting XML utilities
  namespace XML {

    extern const Tag_t Unicode_NULL;
    extern const Tag_t Unicode_empty;
    extern const Tag_t Unicode_star;
    extern const Tag_t Unicode_PI;
    extern const Tag_t Unicode_TWOPI;

    UNICODE(0);
    UNICODE(1);
    UNICODE(2);
    UNICODE(3);
    UNICODE(4);
    UNICODE(5);
    UNICODE(6);
    UNICODE(7);
    UNICODE(8);
    UNICODE(9);

    UNICODE (a);
    UNICODE (A);
    UNICODE (Air);
    UNICODE (angle);
    UNICODE (alignment);
    UNICODE (alignments);
    UNICODE (alpha);
    UNICODE (alpha1);
    UNICODE (alpha2);
    UNICODE (alpha3);
    UNICODE (alpha4);
    UNICODE (arb8);
    UNICODE (arg);
    UNICODE (argument);
    UNICODE (assembly);
    UNICODE (atom);
    UNICODE (attributes);
    UNICODE (aunit);
    UNICODE (author);

    UNICODE (b);
    UNICODE (B);
    UNICODE (barrel);
    UNICODE (barrel_envelope);
    UNICODE (beampipe);
    UNICODE (beta);
    UNICODE (box);

    UNICODE (c);
    UNICODE (C);
    UNICODE (calorimeter);
    UNICODE (cartesian_grid_xy);
    UNICODE (chamber);
    UNICODE (chambers);
    UNICODE (check);
    UNICODE (checksum);
    UNICODE (cm);
    UNICODE (coefficient);
    UNICODE (coefficients);
    UNICODE (color);
    UNICODE (combine_hits);
    UNICODE (combineHits);
    UNICODE (comment);
    UNICODE (component);
    UNICODE (composite);
    UNICODE (cone);
    UNICODE (constant);
    UNICODE (crossing_angle);
    UNICODE (cut);

    UNICODE (d);
    UNICODE (D);
    UNICODE (define);
    UNICODE (delta);
    UNICODE (deltaphi);
    UNICODE (deltatheta);
    UNICODE (depth);
    UNICODE (desnity);
    UNICODE (detector);
    UNICODE (detectors);
    UNICODE (dim_r);
    UNICODE (dim_x);
    UNICODE (dim_y);
    UNICODE (dim_z);
    UNICODE (dimensions);
    UNICODE (dipole_coeff);
    UNICODE (disk);
    UNICODE (disks);
    UNICODE (display);
    UNICODE (dr);
    UNICODE (drawing_style);
    UNICODE (drawingStyle);
    UNICODE (dx);
    UNICODE (dy);
    UNICODE (dz);

    UNICODE (e);
    UNICODE (E);
    UNICODE (ecut);
    UNICODE (element);
    UNICODE (eltube);
    UNICODE (end);
    UNICODE (end_module);
    UNICODE (end_modules);
    UNICODE (endcap);
    UNICODE (endphi);
    UNICODE (epsilon);
    UNICODE (eunit);
    UNICODE (end_x);
    UNICODE (end_y);
    UNICODE (end_z);

    UNICODE (f);
    UNICODE (F);
    UNICODE(false);
    UNICODE (field);
    UNICODE (fields);
    UNICODE (field_name);
    UNICODE (file);
    UNICODE (first);
    UNICODE (firstposition);
    UNICODE (firstrotation);
    UNICODE (formula);
    UNICODE (fraction);
    UNICODE (funit);

    UNICODE (g);
    UNICODE (G);
    UNICODE (gamma);
    UNICODE (gap);
    UNICODE (gas);
    UNICODE (generator);
    UNICODE (gdml);
    UNICODE (gdmlFile);
    UNICODE (glass);
    UNICODE (global);
    UNICODE (global_grid_xy);
    UNICODE (grid_size_x);
    UNICODE (grid_size_y);
    UNICODE (grid_size_z);
    UNICODE (grid_size_phi);
    UNICODE (grid_xyz);
    UNICODE (gridSizePhi);
    UNICODE (gridSizeX);
    UNICODE (gridSizeY);
    UNICODE (gridSizeZ);

    UNICODE (h);
    UNICODE (H);
    UNICODE (half_x);
    UNICODE (half_y);
    UNICODE (half_z);
    UNICODE (header);
    UNICODE (height);
    UNICODE (hits_collection);
    UNICODE (hype);

    UNICODE (i);
    UNICODE (I);
    UNICODE (id);
    UNICODE (iddict);
    UNICODE (identity_rot);
    UNICODE (identity_pos);
    UNICODE (idfield);
    UNICODE (idspec);
    UNICODE (idspecref);
    UNICODE (include);
    UNICODE (includes);
    UNICODE (incoming_r);
    UNICODE (info);
    UNICODE (inner);
    UNICODE (inner_field);
    UNICODE (inner_r);
    UNICODE (inner_radius);
    UNICODE (inner_stereo);
    UNICODE (inner_z);
    UNICODE (insideTrackingVolume);
    UNICODE (intersection);
    UNICODE (InvisibleNoDaughters);
    UNICODE (InvisibleWithDaughters);

    UNICODE (j);
    UNICODE (J);

    UNICODE (k);
    UNICODE (K);

    UNICODE (l);
    UNICODE (L);
    UNICODE (label);
    UNICODE (ladder);
    UNICODE (layer);
    UNICODE (layers);
    UNICODE (lcdd);
    UNICODE (lccdd);
    UNICODE (length);
    UNICODE (limit);
    UNICODE (limits);
    UNICODE (limitset);
    UNICODE (limitsetref);
    UNICODE (line_style);
    UNICODE (lineStyle);
    UNICODE (local);
    UNICODE (lunit);

    UNICODE (m);
    UNICODE (M);
    UNICODE (material);
    UNICODE (materialref);
    UNICODE (materials);
    UNICODE (member);
    UNICODE (MeV);
    UNICODE (mm);
    UNICODE (module);
    UNICODE (modules);
    UNICODE (module_component);
    UNICODE (module_envelope);
    UNICODE (moduleHeight);
    UNICODE (modulePitch);
    UNICODE (modulePosX);
    UNICODE (modulePosY);
    UNICODE (moduleWidth);

    UNICODE (n);
    UNICODE (N);
    UNICODE (NIL);
    UNICODE (name);
    UNICODE (nmodules);
    UNICODE (nModules);
    UNICODE (nonprojective_cylinder);
    UNICODE (nPads);
    UNICODE (nphi);
    UNICODE (ntheta);
    UNICODE (number);
    UNICODE (numsides);
    UNICODE (nz);

    UNICODE (o);
    UNICODE (O);
    UNICODE (offset);
    UNICODE (overlap);
    UNICODE (outer);
    UNICODE (outer_field);
    UNICODE (outer_r);
    UNICODE (outer_radius);
    UNICODE (outer_stereo);
    UNICODE (outer_z);
    UNICODE (outgoing_r);
    UNICODE (outst);

    UNICODE (p);
    UNICODE (P);
    UNICODE (padPitch);
    UNICODE (pads);
    UNICODE (para);
    UNICODE (paraboloid);
    UNICODE (param);
    UNICODE (params);
    UNICODE (particles);
    UNICODE (phi);
    UNICODE (phi0);
    UNICODE (phi1);
    UNICODE (phi_tilt);
    UNICODE (phiBins);
    UNICODE (phi_size_max);
    UNICODE (physvol);
    UNICODE (physvolid);
    UNICODE (plugin);
    UNICODE (plugins);
    UNICODE (polyhedra);
    UNICODE (polycone);
    UNICODE (position);
    UNICODE (positionref);
    UNICODE (projective_cylinder);
    UNICODE (projective_zplane);
    UNICODE (properties);
    UNICODE (psi);

    UNICODE (q);
    UNICODE (Q);

    UNICODE (r);
    UNICODE (R);
    UNICODE (r_size);
    UNICODE (r0);
    UNICODE (rad);
    UNICODE (radian);
    UNICODE (radius);
    UNICODE (radiator);
    UNICODE (rbg);
    UNICODE (rc);
    UNICODE (readout);
    UNICODE (readouts);
    UNICODE (ref);
    UNICODE (reflect);
    UNICODE (reflect_rot);
    UNICODE (region);
    UNICODE (regions);
    UNICODE (regionref);
    UNICODE (repeat);
    UNICODE (rhi);
    UNICODE (ring);
    UNICODE (rlo);
    UNICODE (rmax);
    UNICODE (rmax1);
    UNICODE (rmax2);
    UNICODE (rmin);
    UNICODE (rmin1);
    UNICODE (rmin2);
    UNICODE (RL);
    UNICODE (row);
    UNICODE (rpc);
    UNICODE (RowID);
    UNICODE (rowHeight);
    UNICODE (rowPitch);
    UNICODE (rphi_layout);
    UNICODE (rotation);
    UNICODE (rotationref);
    UNICODE (rtor);

    UNICODE (s);
    UNICODE (S);
    UNICODE (scintillator);
    UNICODE (sd);
    UNICODE (sdref);
    UNICODE (second);
    UNICODE (segmentation);
    UNICODE (sensitive);
    UNICODE (sensitive_detector);
    UNICODE (sensitive_detectors);
    UNICODE (sensor);
    UNICODE (sequence);
    UNICODE (setup);
    UNICODE (shape);
    UNICODE (show_daughters);
    UNICODE (showDaughters);
    UNICODE (size);
    UNICODE(signed);
    UNICODE (skew);
    UNICODE (slice);
    UNICODE (slices);
    UNICODE (solid);
    UNICODE (solids);
    UNICODE (solidref);
    UNICODE (spacer);
    UNICODE (sphere);
    UNICODE (status);
    UNICODE (start);
    UNICODE (start_x);
    UNICODE (start_y);
    UNICODE (start_z);
    UNICODE (startphi);
    UNICODE (starttheta);
    UNICODE (stave);
    UNICODE (staves);
    UNICODE (store_secondaries);
    UNICODE (strength);
    UNICODE (structure);
    UNICODE (subtraction);
    UNICODE (support);
    UNICODE (system);

    UNICODE (t);
    UNICODE (T);
    UNICODE (theta);
    UNICODE (thetaBins);
    UNICODE (thickness);
    UNICODE (threshold);
    UNICODE (title);
    UNICODE (tube);
    UNICODE (tubes);
    UNICODE (torus);
    UNICODE (tracker);
    UNICODE (tracking_cylinder);
    UNICODE (tracking_volume);
    UNICODE (trap);
    UNICODE (trd);
    UNICODE(true);
    UNICODE (tubs);
    UNICODE (type);

    UNICODE (u);
    UNICODE (U);
    UNICODE(union);
    UNICODE (unit);
    UNICODE (useForHitPosition);
    UNICODE (url);

    UNICODE (v);
    UNICODE (V);
    UNICODE (v1x);
    UNICODE (v1y);
    UNICODE (v2x);
    UNICODE (v2y);
    UNICODE (v3x);
    UNICODE (v3y);
    UNICODE (v4x);
    UNICODE (v4y);
    UNICODE (v5x);
    UNICODE (v5y);
    UNICODE (v6x);
    UNICODE (v6y);
    UNICODE (v7x);
    UNICODE (v7y);
    UNICODE (v8x);
    UNICODE (v8y);
    UNICODE (Vacuum);
    UNICODE (value);
    UNICODE (verbose);
    UNICODE (version);
    UNICODE (vis);
    UNICODE (visible);
    UNICODE (visref);
    UNICODE (volume);
    UNICODE (volumeref);

    UNICODE (w);
    UNICODE (W);
    UNICODE (wedge);
    UNICODE (width);
    UNICODE (world);
    UNICODE (world_box);
    UNICODE (world_volume);

    UNICODE (x);
    UNICODE (X);
    UNICODE (x_offset);
    UNICODE (x0);
    UNICODE (x1);
    UNICODE (X1);
    UNICODE (x2);
    UNICODE (X2);
    UNICODE (x3);
    UNICODE (x4);
    UNICODE (xhalf);
    UNICODE (xmax);
    UNICODE (xmin);
    UNICODE (xml);

    UNICODE (y);
    UNICODE (Y);
    UNICODE (y0);
    UNICODE (y1);
    UNICODE (Y1);
    UNICODE (y2);
    UNICODE (Y2);
    UNICODE (y3);
    UNICODE (y4);
    UNICODE (yhalf);
    UNICODE (ymin);
    UNICODE (ymax);
    UNICODE (y_offset);

    UNICODE (z);
    UNICODE (Z);
    UNICODE (z_layout);
    UNICODE (z_length);
    UNICODE (z_offset);
    UNICODE (z0);
    UNICODE (z1);
    UNICODE (z2);
    UNICODE (z3);
    UNICODE (z4);
    UNICODE (zhalf);
    UNICODE (zmin);
    UNICODE (zmax);
    UNICODE (zplane);
    UNICODE (zstart);

  }
}
