# $Id: run1.mac,v 1.2 2000-11-21 10:59:42 maire Exp $
#
# Macro file for "exampleN03.cc"
# 
# can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
/control/verbose 1
/control/saveHistory
#
/run/verbose 2
/event/verbose 0
/tracking/verbose 1
# 
# muon 300 MeV to the direction (1.,0.,0.)
# 3 events
#
/generator/select gun

/gun/direction 1. 1. 1.
/gun/particle mu+
/gun/energy 1000 MeV
/run/beamOn 3
