name: Bug Report
description: Use this template for reporting Bugs or Errors
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: To facilitate faster and easier response to your issue please provide in addition to the description of the issue also the following information
  - type: checkboxes
    id: check-duplicates
    attributes:
      label: Check duplicate issues.
      description: Please search in [GitHub](https://github.com/aidasoft/dd4hep/issues?q=is%3Aissue) or existing reports of your issue and their solutions
      options:
        - label: Checked for duplicates
    validations:
      required: true
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: A short description of what you are trying to achieve
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System and Version
      placeholder: "e.g. Alma Linux 9"
    validations:
      required: true
  - type: input
    id: compiler-version
    attributes:
      label: compiler
      placeholder: "e.g. GCC 13"
    validations:
      required: true
  - type: input
    id: root-version
    attributes:
      label: ROOT Version
      placeholder: e.g. 6.10/02
    validations:
      required: true
  - type: input
    id: dd4hep-version
    attributes:
      label: DD4hep Version
      placeholder: "tag, commit ID, or GitHub branch"
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: Reproducer
      description: |
        Step-by-step instructions to reproduce the issue.
        - If possible, as a self-contained  list of instructions starting from a clean shell
          - git checkout, setup environment (Geant4/ROOT version, LCG/iLCSoft/Key4hep release), cmake, build, run...
        - Don't forget to attach any required input files
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
    validations:
      required: false
