//==========================================================================
//  AIDA Detector description implementation 
//--------------------------------------------------------------------------
// Copyright (C) Organisation europeenne pour la Recherche nucleaire (CERN)
// All rights reserved.
//
// For the licensing terms see $DD4hepINSTALL/LICENSE.
// For the list of contributors see $DD4hepINSTALL/doc/CREDITS.
//
//==========================================================================
//
//  LinkDef.h
//
//  Created by Pere Mato on 22/1/12.
//
// Keep this file EMPTY. All CINT statements can be put in header files preceeding this one.....
//

#ifdef __GNUC__

//--------------------------------------------------------------------------
//  These are the common warnings, which are generated by rootcling
//  and which cannot be avoided at all. We hence disable them in the
//  corresponding compilation units to reduce annoying warnings.
//
//  M.Frank
//--------------------------------------------------------------------------

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#pragma GCC diagnostic ignored "-Wdeprecated"
#pragma GCC diagnostic ignored "-Wunused"
#pragma GCC diagnostic ignored "-Woverlength-strings"

#endif

