include ( FindPackageHandleStandardArgs )

find_package(PythonInterp  REQUIRED)
find_package(PythonLibs    REQUIRED)

if (PYTHONLIBS_FOUND)
  get_filename_component(PYTHON_LIBRARY_DIR  ${PYTHON_LIBRARIES} PATH)
  set(PYTHON_LIBRARY_DIR  ${PYTHON_LIBRARY_DIR})
  set(PYTHON_LIBRARIES    ${PYTHON_LIBRARIES})
  set(PYTHON_INCLUDE_DIRS ${PYTHON_INCLUDE_DIRS})
else()
  message(STATUS "PYTHON ****NOT**** FOUND")
endif()
find_package_handle_standard_args(PYTHON DEFAULT_MSG PYTHON_INCLUDE_DIR)
mark_as_advanced(PYTHON_FOUND PYTHON_INCLUDE_DIRS)
