message(STATUS " *** Gaudi listcomponents: Generate map for ${libname} ..." )
  #
  #  Running listcomponents from DD4hep
  #
  MESSAGE( STATUS " *** MakeGaudiMap.cmake run command : ${DD4HEP_LISTCOMPONENTS_CMD} -o ${rootmapfile} ${libname}
                   WORKING_DIRECTORY ${LIBRARY_LOCATION} "
    ) 
  GET_FILENAME_COMPONENT(GAUDI_LISTCOMP_INSTALL ${DD4HEP_LISTCOMPONENTS_CMD} DIRECTORY)
  if(APPLE)
    SET ( ENV{DYLD_LIBRARY_PATH} ${LIBRARY_LOCATION}:$ENV{DYLD_LIBRARY_PATH}:$ENV{DD4HEP_LIBRARY_PATH} )
    ##EXECUTE_PROCESS( COMMAND echo DYLD_LIBRARY_PATH = $ENV{DYLD_LIBRARY_PATH} )
  else()
    SET ( ENV{LD_LIBRARY_PATH} ${LIBRARY_LOCATION}:${GAUDI_LISTCOMP_INSTALL}:$ENV{LD_LIBRARY_PATH} )
  endif()
  # EXECUTE_PROCESS( COMMAND echo LD_LIBRARY_PATH = $ENV{LD_LIBRARY_PATH} )
  EXECUTE_PROCESS( COMMAND 
    ${DD4HEP_LISTCOMPONENTS_CMD} -o ${rootmapfile} ${libname}
    WORKING_DIRECTORY ${LIBRARY_LOCATION}
    )
