name: macOS

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches-ignore:
      - dependabot/**

jobs:
  macOS:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
    - name: Brew install
      run: |
        brew install root boost ninja
        pip install pytest
    - name: Compile
      run: |
        mkdir build
        cd build
        cmake -GNinja -DDD4HEP_USE_GEANT4=OFF -DBoost_NO_BOOST_CMAKE=ON -DDD4HEP_USE_LCIO=OFF -DBUILD_TESTING=ON -DDD4HEP_USE_XERCESC=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -DDD4HEP_RELAX_PYVER=ON ..
        ninja

  default:
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        LCG: ["LCG_110/arm64-mac15-clang170-opt",
              "dev3/arm64-mac15-clang170-opt",
              "dev4/arm64-mac15-clang170-opt"]
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
    - uses: cvmfs-contrib/github-action-cvmfs@ea996d5ba388b05d4b97f07569d677eac442f20a
      with:
        cvmfs_repositories: sft.cern.ch,sft-nightlies.cern.ch,geant4.cern.ch
    - uses: aidasoft/run-lcg-view@d8db17c61216548c9192889942d46ff2d7c3a3b6
      with:
        release-platform: ${{ matrix.LCG }}
        ccache-key: ccache-${{ matrix.LCG }}
        run: |
          mkdir build
          cd build
          unset CPATH
          echo "::group::CMakeConfig"
          # Common CMake options
          source ../.github/scripts/common_cmake_opts.sh
          echo "::group::CMakeConfig C++20"
          cmake \
            ($COMMON_CMAKE_OPTS) \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_CXX_STANDARD=20 \
            ..
          if [[ ${{ matrix.LCG }} =~ dev[34] ]]; then
            echo "::group::CMakeConfig 2"
            cmake \
              -DDD4HEP_HEPMC3_COMPRESSION_SUPPORT=ON \
              -DDD4HEP_USE_G4HEPEM=ON \
              ..
          fi
          echo "::group::Compile"
          ninja install
          ccache -s
          . ../bin/thisdd4hep.sh
          echo "::group::Test"
          ctest --output-on-failure -j"$(getconf _NPROCESSORS_ONLN)" --output-junit TestResults_1.xml
          echo "::group::CMakeExamples"
          cd ../examples/
          mkdir build
          cd build
          source ../../.github/scripts/common_cmake_opts.sh
          cmake \
            ($COMMON_EXAMPLES_CMAKE_OPTS) \
            -DCMAKE_CXX_STANDARD=20 \
            ..
          echo "::group::CompileExamples"
          ninja install
          ccache -s
          echo "::group::TestExamples"
          ctest --output-on-failure -j"$(getconf _NPROCESSORS_ONLN)" --output-junit TestResults_2.xml
    - name: Prepare Artifact Name
      if: success() || failure()
      run: |
          artifact_name="${{ matrix.LCG }}"
          artifact_name=$(echo -n "${artifact_name}" | sed -e 's@/@@g')
          echo "ARTIFACT_NAME=${artifact_name}" >> $GITHUB_ENV
    - name: Upload test results
      if: success() || failure()
      uses: actions/upload-artifact@v7
      with:
        name: Test Results ${{ env.ARTIFACT_NAME }}
        path: |
           /home/runner/work/DD4hep/DD4hep/build/TestResults_1.xml
           /home/runner/work/DD4hep/DD4hep/examples/build/TestResults_2.xml
