name: python

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches-ignore:
      - dependabot/**

jobs:
  python-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        LCG: ["dev4/x86_64-el9-gcc13-opt"]
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - uses: cvmfs-contrib/github-action-cvmfs@10197e000cc0add8e54ac4fb73d3ed44e2de72b4
    - uses: aidasoft/run-lcg-view@d8db17c61216548c9192889942d46ff2d7c3a3b6
      with:
        release-platform: ${{ matrix.LCG }}
        run: |
          echo "RUNNING FLAKE8 CHECK"
          find . -name "*.py" -exec flake8 {} +
